// <auto-generated />
using Data.UrLocal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace UrLocal.Migrations
{
    [DbContext(typeof(UrLocalContext))]
    partial class UrLocalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("UrLocal.Bars", b =>
                {
                    b.Property<int>("barId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("barLocation")
                        .HasColumnType("text");

                    b.Property<string>("barName")
                        .HasColumnType("text");

                    b.Property<bool>("beerCheck")
                        .HasColumnType("boolean");

                    b.Property<int>("complexity")
                        .HasColumnType("integer");

                    b.Property<int>("craftSlide")
                        .HasColumnType("integer");

                    b.Property<double>("lqBeer")
                        .HasColumnType("double precision");

                    b.Property<double>("lqMeal")
                        .HasColumnType("double precision");

                    b.Property<bool>("spiritCheck")
                        .HasColumnType("boolean");

                    b.Property<double>("uqBeer")
                        .HasColumnType("double precision");

                    b.Property<double>("uqMeal")
                        .HasColumnType("double precision");

                    b.Property<bool>("wineCheck")
                        .HasColumnType("boolean");

                    b.HasKey("barId");

                    b.ToTable("bars");
                });

            modelBuilder.Entity("UrLocal.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("BeerCheck")
                        .HasColumnType("boolean");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<double>("PriceRange")
                        .HasColumnType("double precision");

                    b.Property<bool>("SpiritCheck")
                        .HasColumnType("boolean");

                    b.Property<bool>("WineCheck")
                        .HasColumnType("boolean");

                    b.Property<int>("craftSlide")
                        .HasColumnType("integer");

                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
